# -*- coding: utf-8 -*-
"""EX_6 Kritigoma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MDjqkhvne-0JqsJG5hhINXnSz8cdeEUF
"""

import pandas as pd
import numpy as np
import csv
################# QUES 1 #################

#1)
from random import random, seed
#seed(0)
L = [ int(random()*10) for i in range(10) ]
print("list l:\n ", L, "\n")

with open("./data_int.txt", mode = 'w') as f:
    #f.write(str(L))
    for item in L:
        f.write("%s " % item)

print("loded txt list file:")        
!cat ./data_int.txt 
print('\n')

#2) 
b= np.random.random((5,5))
mat = np.matrix(b)
print("random 5*5 matrix:\n", mat, "\n")    
with open('data_float.txt','wb') as f:
    #f.write(str(mat))
    for line in mat:
        np.savetxt(f, line, fmt='%.2f')

print("data_float:")
!cat ./data_float.txt 
print('\n')

#3)
f = open('./data_float.txt', 'r')
textContent = f.read()
print("loded txt file: \n", textContent)
f.close()



import zlib
lines = textContent.splitlines()
rawContent = [line.split(' ') for line in lines]
rows = zip(*[rawContent]*1)
with open('data_float.csv', 'w') as out_file:
    writer = csv.writer(out_file)
    for row in rows:
        writer.writerows(row)
print("csv file: ")
!cat ./data_float.csv 
print('\n')

############# QUES 2 ########################
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json -P ./data/
import json

############################# QUes 2 #################
d = json.load(open('./data/user_data.json.1'))

header = ["ID","JobTitle","EmailAddress","FirstNameLastName","CreditCard", "CreditCardType"]
l=[]
for a in d:
    if a['CreditCardType'] == 'American Express':
        array= [a["ID"], a["JobTitle"], a["EmailAddress"],a["FirstNameLastName"],a["CreditCard"],a["CreditCardType"]]
        l.append(array)


with open('jsonfiltered.csv','w') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(header)
    writer.writerow(l) 

print("csv file: ")
!cat jsonfiltered.csv

!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv -P ./data/

################## QUES 3  ##################

file_1 = "./data/mushrooms_categorized.csv"
data_1 = pd.read_csv(file_1)


gb = data_1.groupby(['class']).mean()

data_frame = pd.DataFrame(gb)

data_frame.to_json(r'./export_mean_json.json', orient = 'index')

!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat -P ./data/

############## QUES 4 #####################3
import math as m

with open('./data/credit_card.dat', 'rb') as file:
    file_content = file.readlines()

    allcarts =[]
    word_counter = 0
    word_size = 8 
    total_digitnumber = 16+3 
    digit_length = 6         

    for row in file_content:

        if(round(len(row)/digit_length) >= total_digitnumber):

            utf_string = row.decode("utf-8")  

            utf_string = utf_string[:-4]  

            start_index = 0
            card_number=[]

            for i in range(total_digitnumber):
                end_index = start_index + digit_length
                digits_4 = utf_string[start_index:end_index]
                card_number.append(digits_4)
                start_index += digit_length    

            credit_card = ""
            for i in range(total_digitnumber):
                credit_card += chr(int(card_number[i],2))

            allcarts.append(credit_card)

    print("Number of all the Credit Card is :\n") 
    for i in allcarts:
        print(i, "\n")