# -*- coding: utf-8 -*-
"""01ex_introduction.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CSSD6ppAFprgnDUyJ8ESdaN4KK-NnRO4
"""

#EX1
#a
for i in range(1, 101):
    if i %15 == 0:
        print("Hello World")
    elif i %3 == 0:
        print("Hello")
    elif i %5 == 0:
        print("World")
    else:
        print(i)
  
#b

my_tuple=()
x = list(my_tuple)
for i in range(101):
  if i%15==00:
    x.append("Phthon works")
  elif i%3==0:
    x.append("Python")
  elif i%5==0:
    x.append("work")
  else:
   x.append(i)
print(tuple(x))

#EX2
x= input("set a value for x ")
y= input("set a value for y ")
x, y = y, x
print("x= ",x)
print("y= ", y)

#EX3
import math
u=(1,10)
v=(0,9)
d=math.sqrt(((u[0]-v[0])**2)+((u[1]-v[1])**2))
print (d)
d=math.sqrt(((u[0]-v[0])**2)+((u[1]-v[1])**2))
print ("Distance= ",d)

#EX4
s1= "Write a program that prints the numbers from 1 to 100. \
But for multiples of three print Hello instead of the number and for the multiples of five print World. \
For numbers which are multiples of both three and five print HelloWorld."
s2= "The quick brown fox jumps over the lazy dog"
count_s1 , count_s2= dict() , dict()
for a in s1:
    count_s1[a]=count_s1.get(a,0) +1
for a in s2:
    count_s2[a]=count_s2.get(a,0) +1
print(f"Letter count of S1:\n{count_s1} \n\nLetter count of S2:\n{count_s2}")

#EX5
l = [36, 45, 58, 3, 74, 96, 64, 45, 31, 10, 24, 19, 33, 86, 99, 18, 63, 70, 85, 85, 63, 47, 56, 42, 70, 84, 88, 55, 20, 54, 8, 56, 51, 79, 81, 57, 37, 91, 1, 84, 84, 36, 66, 9, 89, 50, 42, 91, 50, 95, 90, 98, 39, 16, 82, 31, 92, 41, 45, 30, 66, 70, 34, 85, 94, 5, 3, 36, 72, 91, 84, 34, 87, 75, 53, 51, 20, 89, 51, 20]
sum=0
i=0
q=[]
while i<len(l):
	if l.count(l[i])==1:
		q.append(l[i])
		sum=sum+1
	i=i+1
print("The number of unique elements:", sum)
print("These numbers are:")
print(q)

#EX6
a=input("a = ")
b=input("b = ")
try:
	a=float(a)
	if(a%1==0):
       		a=int(a)
	b=float(b)
	if(b%1==0):
        	b=int(b)
	sum=a+b
	print("a+b=", sum)
except:
	print("The operation can not be done.")

#EX7
#a

list=[]
for i in range(11):
  list.append(i**3)
print(list)


#b

l2 = [x**3 for x in range(11)]

print(l2)



#EX8

print([(i,j) for i in range(3) for j in range(4)])

#EX9

x= ([(a,b,c) for a in range (1,100) for b in range(1,100) for c in range(1,100) if c**2 == a**2 + b**2])
print(x)

#EX10


x= input("Please type the value: ")
l=[]
sum=0
norm=[]
for i in range(int(x)):
  y= input("Please type the value: ")
  l.append(int(y))
print(l)
for j in range(len(l)):
  norm.append(l[j]**2)
print(norm)
for k in norm:
  sum+= k
print(sum)
for z in range(len(norm)):
  norm[z]= (norm[z])/sum
print(norm)

#EX11


fib=[0,1]
while len(fib)<20:
	fib.append(fib[len(fib)-1]+fib[len(fib)-2])
	fib.append(fib[len(fib)-1]+fib[len(fib)-2])
print(fib)