# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v31vWumFv74avH99oSfGZ1Izzm7ozm-K
"""

# 01ex_introduction_es01
x = 1
while x <= 100:
    if x % 3 == 0 and x % 5 == 0:
        print("HelloWorld")
    elif x % 3 == 0:
        print("Hello")
    elif x % 5 == 0:
        print("World")
    else:
        print(x)
    x += 1

# 01ex_introduction_es02
x = input("Enter the value of x ")
y = input("Enter the value of y ")
x,y = y,x
print("x = " + x)
print("y = " + y)

# 01ex_introduction_es03
import math

x1 = float(input("enter X1:"))
x2 = float(input("enter x2:"))
y1 = float(input("enter y1:"))
y2 = float(input("enter y2:"))
distance = math.sqrt((x1-y1)**2 + (x2-y2)**2)

print(distance)

# 01ex_introduction_es04
s1 = "Write a program that prints the numbers from 1 to 100. But for multiples of three print Hello instead of the number and for the multiples of five print World. For numbers which are multiples of both three and five print HelloWorld."
s2 = "The quick brown fox jumps over the lazy dog."
s = set(str(s1)+str(s2))

test= str(s1) + str(s2)

for i in s:
  counter = test.count(i)
  if i == ' ':
    i = 'Space'
  print(counter, i)

# 01ex_introduction_es05
list=[36, 45, 58, 3, 74, 96, 64, 45, 31, 10, 24, 19, 33, 86, 99, 18, 63, 70, 85,
 85, 63, 47, 56, 42, 70, 84, 88, 55, 20, 54, 8, 56, 51, 79, 81, 57, 37, 91,
 1, 84, 84, 36, 66, 9, 89, 50, 42, 91, 50, 95, 90, 98, 39, 16, 82, 31, 92, 41,
 45, 30, 66, 70, 34, 85, 94, 5, 3, 36, 72, 91, 84, 34, 87, 75, 53, 51, 20, 89, 51, 20]

print(f"The unique numbers are \n{set(list)} \n No of unique numbers are {len(set(list))}")

# 01ex_introduction_es06
variable_1 = 1
variable_2 = 3.6

try:
    if type(variable_1) is str or type(variable_2) is str:
      variable_1, variable_2 = str(variable_1), str(variable_2)
    print(variable_1+variable_2)
except:
    print("Code Crash")

# 01ex_introduction_es07
cubes = []

for x in range(0, 10):
    cubes = (x**3)
    print(cubes)
# list comprehension
cubes = [x**3 for x in range(0, 10)]
print("List comprehension:", cubes)

# 01ex_introduction_es08

print([(i,j)for i in range(3) for j in range(4)])

# 01ex_introduction_es09
print([(a,b,c)for a in range(0,100) for b in range(0,100) for c in range(0,100) if c**2 == a**2 + b**2])

# 01ex_introduction_es10
x = float(input("enter x:"))
y = float(input("enter y:"))
z = float(input("enter z:"))
vector = (x,y,z)

sum = 0
for i in vector:
    sum = sum + i**2
distance = sum**0.5
print(f"The normalized vector is: \n{[i/distance for i in vector]}")

# 01ex_introduction_es11
f=[0, 1]
a,b = 0,1
for i in range(18):
    f.append(a+b)
    a,b = b,a+b

print("Fibonacci sequence", f)
