# -*- coding: utf-8 -*-
"""01ex_introduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0ZYba6IuCHCcPJ8klfcV79TOXdpyhgk

ex1 
a:
"""

for i in range(101):
  if i%15==00:
    print("Hello world")
    continue
  if i%3==0:
    print("Hello")
    continue
  if i%5==0:
    print("World")
    continue
  else:
    print(i)

"""ex1
b:
"""

tuple1=()
y = list(tuple1)
for i in range(101):
  if i%15==00:
    y.append("Phthon works")
    continue
  if i%3==0:
    y.append("Python")
    continue
  if i%5==0:
    y.append("work")
    continue
  else:
   y.append(i)
t=tuple(y)
print(t)

"""ex2"""

x = input("input:")
y= input("input2:")
x,y=y,x
print(y,x)

"""ex3"""

import math
def myfunction():
  x1=int(input("x1"))
  y1=int(input("y1"))
  x2=int(input("x2"))
  y2=int(input("y2"))
  tup1=(x1,y1)
  tup2=(x2,y2)
  distance=math.sqrt((abs(tup1[0]-tup2[0])**2)+(abs(tup1[1]-tup2[1])**2))
  print(distance)

myfunction()

"""ex4"""

x=input("enter your letter")
y=input("enter your text")
counter=0
for i in y:
  if i==x.lower() or i==x.upper():
    counter+=1
print(counter)

"""ex5"""

list1 = [36, 45, 58, 3, 74, 96, 64, 45, 31, 10, 24, 19, 33, 86, 99, 18, 63, 70, 85,
 85, 63, 47, 56, 51, 20,20,20,20]
l=[]
for i in range(len(list1)):
  #print("x=",list1[i],i)
  count=0

  for j in range(i+1,len(list1)):
    if list1[i]==list1[j]:
      #print('d',j,list1[j])
      count=count+1
      #print('count',count)
  if count==0:
    l.append(list1[i])

print('new list with unique items    ')
print(l) 
print('number of unique items')
print(len(l))

"""ex6"""

x=input('enter firs input')
y=input('enter second input')
def calculate(x,y):
  try:
    X1=float(x)
  except:
    print('not int')
    try:
      Y1=int(y)
      return(X1+Y1)
    except:
      print('y not int adn they are string')
      return(x+y)
  try:
    Y1=float(y)
    print(X1+Y1)
  except:
    return('interger or flout can not add to string')
calculate(x,y)

"""ex7
a:
"""

l=[]
for i in range(11):
  l.append(i**3)
print(l)

"""ex7
b:
"""

newlist = [x**3 for x in range(11)]

print(newlist)

"""ex 8"""

a=[(x,y)for x in range(3) for y in range(4)]
print(a)

"""ex 9 first approach"""

s=[]
c, m = 0, 2
counter=0
number=2
while counter < 100 :
        for n in range(1, m) :
            a = number * number - n * n
            b = 2 * number * n
            counter = number * number + n * n
            if counter > 100 :
                break
            s.append((a,b,counter))
        number = number + 1
a=tuple(s)       
print(a)

"""ex9
not that al the number that are valid in a**2+b**2=c**2
are some coefficient of (3*n,4*n,5*n) for exmale when n=2 (6,8,10)or n=3(9,12,15)...
"""

#81
lis=[]
import math
a,b,c=3,4,5
limit=int(100/5)
for i in range(limit):
  lis.append((a*i,b*i,c*i))
t=tuple(lis)
print(t)

"""ex 10"""

#9
x=input('input vector dimention')
lis=[]
sum=0
norm=[]
for i in range(int(x)):
  y=input(' input ith elemet of vector')
  lis.append(int(y))
print(lis)
for j in range(len(lis)):
  norm.append(lis[j]**2)
print(norm)
for k in norm:
  sum+=k
print(sum)
for z in range(len(norm)):
  norm[z]=(norm[z])/sum
print(norm)

"""ex11"""

#10
n=20
a = 1
b = 1
if n == 1:
  print(a)
else:
  print(a)
  print(b)
  for i in range(2,n):
    c = a + b
    a = b
    b = c
    print(c)