# -*- coding: utf-8 -*-
"""05ex_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-RrlTrhwZvMyz5mhgdW-6EYCTB7E9OnD
"""

import pandas as pd
import numpy as np

!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt

file= "data_000637.txt"
data= pd.read_csv(file)
data

"""#1-"""

df=data.sample(n=40000)

"""#2-"""

print(format(df['BX_COUNTER'].max()))

"""#3-"""

print(25/30)

df['newcolumn']=(df['TDC_MEAS']*0.833)+(df['BX_COUNTER']*25)+(df['ORBIT_CNT']*25)
#df1 = df.assign(A_T=pd.Series(np.array(Time)).values)
print(df)

"""#4-"""

df2=df.copy()
print(df2.sort_values(by='newcolumn')['newcolumn'])
df2['newcolumn']=df2.sort_values(by='newcolumn')['newcolumn']



"""#5-"""

TDC_Count = df.groupby('TDC_CHANNEL').sum()
print(TDC_Count['HEAD'])
T_C=list(TDC_Count['HEAD'])
temp=T_C.copy()
temp.sort(reverse=True)
max_TDC_count= temp[:3]
max_TDC_index=[T_C.index(temp[i]) for i in range(3)]
#print(format(max_TDC_index,max_TDC_count))

"""#6-"""

c=df['ORBIT_CNT'].unique()

print(df['ORBIT_CNT'].sum())

"""#7-"""

print( len(set(list(df2["ORBIT_CNT"]))))
print( len(set(list(df2[df2["ORBIT_CNT"]==139]))))

"""#8-"""

import matplotlib.pyplot as plt
CH1= [df2['TDC_CHANNEL'][i] for i in range(50000) if df2['FPGA'][i] == 0]
CH1.sort()
Counter1=[]
Channels1=[]
for i in range(len(CH1)):
    if CH1[i] not in Channels1:
        Counter1.append(CH1.count(CH1[i]))
        Channels1.append(CH1[i])
    else: continue
plt.plot(Channels1, Counter1)
plt.xlabel('TDC_CHANNEL')
plt.ylabel('Count')
plt.title('FPGA0')
plt.figure()

CH2= [df2['TDC_CHANNEL'][i] for i in range(N) if df2['FPGA'][i] == 1]
CH2.sort()

Counter2=[]
Channels2=[]

for i in range(len(CH2)):
    if CH2[i] not in Channels2:
        Counter2.append(CH2.count(CH2[i]))
        Channels2.append(CH2[i])
    else: continue
plt.plot(Channels2, Counter2)
plt.xlabel('TDC_CHANNEL')
plt.ylabel('Count')
plt.title('FPGA1')
plt.figure()