# -*- coding: utf-8 -*-
"""06ex_OSEMN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_fNzQlWXsitzbZneOd5C0bTeMTwKQRA
"""

import numpy as np
import pandas as pd
import csv

"""#1"""

#list=[12,11,15,14,18]
with open("data_int.txt", "w") as f:
  list=[12,11,15,14,18]
  for i in list:
      f.write(str(i))
      if i != list[-1]: f.write(",")
#from os import system
#system("cat ~/example.txt")
!cat data_int.txt

#mat=np.random.random((5, 5))
with open("data_float.txt","w") as f :
  mat=np.random.random((5, 5))
  for i in mat:
   f.write(str(i))
!cat data_flaot.txt

"""#2"""

!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

import json
data = json.load(open('user_data.json'))
filtered_data=[line for line in data if line.get('CreditCardType') == "American Express" ]
df = pd.DataFrame(data=filtered_data)
df.to_csv("user_data_filtered.csv", sep=',',index=False)
print(df)

"""#3"""

!wget  https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

df = pd.read_csv('mushrooms_categorized.csv')
print(df)

print(df.groupby('class').mean())

import json
with open("mushrooms_categorized.json", "w") as outfile:
#outfile.write()

"""#4"""

!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

df = pd.read_csv('credit_card.dat', header = None)

df

with open('credit_card.dat', 'rb') as f:
    content = f.readlines()
print(content[0])

chr(int('110111',2))

# [[content[lineNumber][i:i+6] for i in range(0, len(content[0])-4, 6)] for lineNumber in range(len(content))]
# [chr(int(content[0][i:i+6],2)) for i in range(0, len(content[0])-4, 6)]
# int(''.join([chr(int(content[0][i:i+6],2)) for i in range(0, len(content[0])-4, 6)]).replace(" ",""))
[int(''.join([chr(int(content[lineNumber][i:i+6],2)) for i in range(0, len(content[0])-4, 6)]).replace(" ","")) for lineNumber in range(len(content)-1)]

"""#5"""

!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ./data/

from IPython.display import Image
Image("images/data_format.png")

df = pd.read_csv("./data/data_000637.txt")

df

binary_file.write( struct.pack('

