# -*- coding: utf-8 -*-
"""ScientificComputingWithPython_Exercise2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BcAAh3iBWj8WafK3sGQ9SX6LSeZKYdh1

# ***Problem No1. Global variables:***

Convert the function  into a function that doesn't use global variables and that does not modify the original list
"""

x = 5

def f(alist):
    for i in range(x):
        alist.append(i)
    return alist

alist = [1, 2, 3]
ans = f(alist)
print(ans)
print(alist) # alist has been changed

"""After changes:"""

x = 5
def f(alist):
  alist = [1, 2, 3]
  for i in range(x):
      alist.append(i)
  return alist

alist = [1, 2, 3]
ans = f(alist)
print(ans)
print(alist) 
print("Now the alist won't change because the function use the copy of that not the original one!")

"""# ***Problem No2. List comprehension:***

Write the following expression using a list comprehension:
"""

ans = list(map(lambda x: x * x, filter(lambda x: x % 2 == 1, range(10))))
print(ans)

"""Answer:"""

l = []
for i in range(1,10):
  if (i % 2 == 1):
    newi = i ** 2 
    l.append(newi)
print(l)

"""# ***Problem No3. Filter list:***

Using the filter() hof, define a function that takes a list of words and an integer n as arguments, and returns a list of words that are shorter than n.
"""

def IsShorter(l):
  m = []
  for i in range(len(l)):
     if int(l[i]) < n:
       m.append(i)
  return m
l = input("Enter a list:").split()
n = int(input("Enter a number to compare with it:"))
print(list(filter(IsShorter, l)))

"""# ***Problem No4.Map dictionary:***

Consider the following dictionary:

lang = {"Python" : 3, "Java" : '', "Cplusplus" : 'test', "Php" : 0.7}

Write a function that takes the above dictionary and uses the map() higher order function to return a list that contains the length of the keys of the dictionary.
"""

def NumberOfKeys(lang):
  count = 0
  l = lang
  for i in range(0,len(l)):
    count += 1
  return count
lang = {"Python" : 3, "Java" : '', "Cplusplus" : 'test', "Php" : 0.7} 
x = list(map(NumberOfKeys,lang))
print("The keys are:", lang.keys())
m = len(x)
print("The count of the keys is:" ,[m])

"""# ***Problem No5.Lambda functions:***

Write a Python program that sorts the following list of tuples using a lambda function, according to the alphabetical order of the first element of the tuple:

language_scores = [('Python', 97), ('Cplusplus', 81), ('Php', 45), ('Java', 32)]

Hint: use the method sort() and its argument key of the list data structure.
"""

language_scores = [('Python', 97), ('Cplusplus', 81), ('Php', 45), ('Java', 32)]
ReverseList = sorted(language_scores, key = lambda x : x[0] , reverse= False)
print("Reverse sorted list: ",ReverseList)
print("original list: ",language_scores)

"""# ***Problem No6.Nested functions***

Write two functions: one that returns the square of a number, and one that returns its cube.

Then, write a third function that returns the number raised to the 6th power, using only the two previous functions.
"""

def Square(x):
  return x ** 2
def Cube(x):
  return x ** 3
def SixthPower(x):
  return Cube(Square(x))
x = int(input("Enter a number:"))
print("The square of the number is:", Square(x))
print("The cube of the number is:", Cube(x))
print("The 6th power of the number is:", SixthPower(x))

"""# ***Problem No7.Decorators:***

Write a decorator named hello that makes every wrapped function print “Hello World!” each time the function is called.

The wrapped function should look like:

@hello

def square(x):

    return x*x
"""

def hello(func):
    def wrapped():
        func()
    return wrapped

@hello
def hello_world():
    print ("Hello World!")
    
hello_world()

"""# ***Problem No8.The Fibonacci sequence (part 2):***

Calculate the first 20 numbers of the Fibonacci sequence using a recursive function.
"""

def Fibonacci(n):
    if n <= 1:
        return n
    return Fibonacci(n-1) + Fibonacci(n-2)
n = 0
for i in range(0,20):
  print(Fibonacci(n))
  n += 1

"""# ***Problem No9.The Fibonacci sequence (part 3):***

Run both the Fibonacci recursive function from the previous exercise, and the Fibonacci function from 01ex that use only for and while loops.

Measure the execution code of the two functions with timeit (link to the doc), for example:

%timeit loopFibonacci(20)

%timeit recursiveFibonacci(20)
"""

#Fibonacci from first exercise:
def Fib(limit):
  FirstNumber = 1 
  SecondNumber = 1
  count = 0
  limit = limit - 2
  while count < limit:
        NextNumber = FirstNumber + SecondNumber
        FirstNumber = SecondNumber
        SecondNumber = NextNumber
        count += 1
  return NextNumber
Fib(20) 
loop='''
def Fib(limit):
  FirstNumber = 0 
  SecondNumber = 1
  count = 0
  limit = limit - 2
  while count < limit:
        NextNumber = FirstNumber + SecondNumber
        FirstNumber = SecondNumber
        SecondNumber = NextNumber
        count += 1
  return NextNumber
Fib(20) 
'''

#Fibonacci from Second exercise:
def Fibonacci(n):
    if n <= 1:
        return n
    return Fibonacci(n-2) + Fibonacci(n-1)
#n = 0
#for i in range(0,20):
  #print(Fibonacci(n))
 # n += 1

recursive='''
def Fibonacci(n):
  if n <= 1:
    return n
  else:
    return Fibonacci(n-1) + Fibonacci(n-2)
Fibonacci(20)
 '''

recursive='''
def Fibonacci(n):
  if n <= 1:
    return n
  else:
    return Fibonacci(n-1) + Fibonacci(n-2)
Fibonacci(20)'''

loop='''def Fib(limit):
  FirstNumber = 1
  SecondNumber = 1
  count = 0
  limit = limit - 2
  while count < limit:
        NextNumber = FirstNumber + SecondNumber
        FirstNumber = SecondNumber
        SecondNumber = NextNumber
        count += 1
  return NextNumber
Fib(20) '''

import timeit
import time
print("The time with recursive function:",timeit.timeit(stmt=recursive,number= 20))
print("The time with loop:",timeit.timeit(stmt=loop,number= 20))

"""OF Course in this case recursive is the better option :))) The time speaks!!!

# ***Problem No10.Class definition:***

Define a class polygon. The constructor has to take a tuple as input that contains the length of each side. The (unordered) input list does not have to have a fixed length, but should contain at least 3 items.

Create appropriate methods to get and set the length of each side

Create a method Perimeter() that returns the Perimeter of the polygon

Create a method getOrderedSides(increasing = True) that returns a tuple containing the length of the sides arranged in increasing or decreasing order, depending on the argument of the method

Test the class by creating an instance and calling the Perimeter() and getOrderedSides(increasing = True) methods.
"""

#This cell of code is jsut for test :)
import operator
class Polygon:
   def __init__(self , components):
            self.x = components 
   def LenComponents(self):
     return len(self.x)
   def Perimeter(self):
     Perimeter = int(0)
     for i in range(len(self.x)):
        Perimeter += int(self.x[i])
     return Perimeter

m = Polygon(input("Enter a list of length of each side:").split())
print("The polygon has", m.LenComponents(),"side.")
print("The Perimeter of polygon:", m.Perimeter())

class Polygon():
  def __init__(self,LenComponents):
     self.LenComponents = LenComponents

  l = []
  def SetSides(self):
    print("Enter the length of each sides one by one: ")
    for i in range(self.LenComponents):
      LengthOfSide = int(input("Enter the length: "))
      self.l.append(LengthOfSide)
    return(self.l)


  def GetEachSides(self):
    return self.l
  def Perimeter(self):
    perimeter = 0
    for i in range(len(self.l)):
      perimeter = perimeter+self.l[i]
    return perimeter
  def getOrderedSides(self,increasing):
    x=sorted(self.l)
    if increasing==True:
      print(x)
    else:
      print(list(reversed(x)))

n = int(input("How many sides do you want? "))
polygon = Polygon(n)
polygon.SetSides()

polygon.GetEachSides()

polygon.Perimeter()

polygon.getOrderedSides(True)

"""# ***Problem No11.Class inheritance:***

Define a class rectangle that inherits from polygon. Modify the constructor, if necessary, to make sure that the input data is consistent with the geometrical properties of a rectangle.

Create a method area() that returns the area of the rectangle.
Test the rectangle class by creating an instance and passing an appropriate input to the constructor.
"""

class Rectangle(Polygon):
  def __init__(self,):
     self.LenComponents=4

  l=[]
  def SetSides(self):
    print("Enter the length of each sides one by one: (Consider the rule of rectangle lengths)")
    for i in range(4):
      LengthOfSide = int(input("Enter the length: "))
      self.l.append(LengthOfSide)
      RectangleSides = sorted(self.l)
    if RectangleSides[0] != RectangleSides[1] and RectangleSides[2] != RectangleSides[3]:
      print("Not valid input for rectangle. Consider that!")
      self.l = []
      self.SetSides()
    return(self.l)
  def area(self):
    return(int((sorted(self.l)[0])) * (int(sorted(self.l[2]))))

rectangle = Rectangle()
rectangle.SetSides()

rectangle.GetEachSides()

rectangle.Perimeter()

rectangle.getOrderedSides(False)